#!/bin/bash

SUBSTR_FIRST_ARG=${1:0:10}
if [ "$SUBSTR_FIRST_ARG" == "--git-dir=" ]
then
  #redirect to git
  /usr/bin/git $@
else
  #do git first
  /usr/bin/git $@
  
  if [ "$1" == "push" ]
  then
    CURRENT_COMMIT=$(/usr/bin/git rev-parse HEAD)
    /usr/bin/git fetch origin > /dev/null  
    REMOTE_BRANCHES_THAT_CONTAIN_CURRENT_COMMIT=$(/usr/bin/git branch -r --contains $CURRENT_COMMIT)
    if [ "${#REMOTE_BRANCHES_THAT_CONTAIN_CURRENT_COMMIT}" -eq 1 ]
    then
      $HOME/own_git_commands/$1/master.sh $@ 
    fi
    #do all this unless master has been pushed
  fi	
fi

#check last arg of git push 


#http://www.xormedia.com/git-check-if-a-commit-has-been-pushed/
#if the commit has been added to the remote changes to the remote branch



